exclude_patterns:
- "**/*.test.js"
- "**/*.png"
- "**/*.svg"
- "**/*.jpg"
- "**/*.css"
- "**/*.scss"
- "**/*.eot"
- "**/*.ico"
- "**/*.jpeg"
- "**/*.JPG"
- "**/*.json"
- "**/*.snap"
- "docscripts/"
- "docs/"
- "coverage/"
- "public/"
- "src/components/"
- "src/assets/"