
sudo: true
env:
  global:
    - CC_TEST_REPORTER_ID=19bd0503e6a203cc0df5e353251ded94a58b6a57d389666378b939cae2daa4b0
    - PYTHON=3.5
before_install:
  - sudo apt-get update
  - sudo apt-get install python3 -y
  - export PYTHON=3.5
  - sudo apt-get install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
  - python --version
  - python -m pip install --upgrade pip
  - sudo pip install sphinx-js
matrix:
  include:
    - language: python
      python: 
      - '3.7'
      - '3.8'
  
    - language: node_js
      node_js:
      - "10.15.3"
 
      cache:
      directories:
      - node_modules

      before_script:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - npm install -g jsdoc


      script:
      - make -C docscripts/ html
      #- npm test -- --coverage --passWithNoTests
  # - touch docs/build/html/.nojekyll
#   - CI=false npm run build

      after_script:
      - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  # - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  - provider: pages
    verbose: true
    github_token: $GITHUB_TOKEN
    edge: true
    local_dir: docs/build/html
    keep_history: true



# language: node_js
# node_js:
#   - "stable"
# cache:
#   directories:
#     - ~/.npm
# before_script:
#   - npm install -g npm@latest
# script:
#   - npm ci
#   - npx jest --ci
