
sudo: true
env:
  global:
    - CC_TEST_REPORTER_ID=19bd0503e6a203cc0df5e353251ded94a58b6a57d389666378b939cae2daa4b0

matrix:
  include:
    - language: python
      python: 2.7
      script:
        - pip install sphinx-js
        - make -C docscripts/ html
    - language: node_js
      node_js:
      - "10.15.3"
      cache:
      directories:
      - node_modules

      before_script:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build

      script:
      - npm test -- --coverage --passWithNoTests
  # - touch docs/build/html/.nojekyll
#   - CI=false npm run build

      after_script:
      - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  # - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  - provider: pages
    verbose: true
    github_token: $GITHUB_TOKEN
    edge: true
    local_dir: docs/build/html
    keep_history: true



# language: node_js
# node_js:
#   - "stable"
# cache:
#   directories:
#     - ~/.npm
# before_script:
#   - npm install -g npm@latest
# script:
#   - npm ci
#   - npx jest --ci
